### ISSUE TITLE
게시글 ERD 작성

### ISSUE THREAD

**Issue by having-dlrow** [fastcampus-711/backend#8]

**Comment by MinKevin** [comment]
![image](https://github.com/fastcampus-711/backend/assets/58409670/c2508110-d31a-4842-b97f-5db28b2fcdaf)

**Comment by MinKevin** [comment]
회의 후 아래와 같이 개선했습니다.
![image](https://github.com/fastcampus-711/backend/assets/58409670/118aca22-0c90-4190-ad07-6ef31e967b2c)

**Comment by having-dlrow** [comment]
https://www.erdcloud.com/d/cA37wpqdvKba6Pfcq
![Image](https://github.com/fastcampus-711/backend/assets/79270228/14db464b-03bd-457c-9353-d300dd55ba57)
